stages:
  - build

.submodule_base: &submodule
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

build:
  <<: *submodule
  stage: build
  script:
    - sh build.sh
  artifacts:
    paths:
      - build
