stages:
  - build

.submodule_base: &submodule
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

build_develop:
  <<: *submodule
  stage: build
  only:
    - develop
  script:
    - sh build.sh
  artifacts:
    paths:
      - build
